services:
    sonata.admin.drone:
        class: Drone\MapBundle\Admin\DroneAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Matériel", label: "Drone" }
        arguments:
            - ~
            - Drone\MapBundle\Entity\Drone
            - ~
        calls:
            - [setTranslationDomain, [DroneAdminBundle]]