services:
    sonata.admin.map:
        class: Drone\MapBundle\Admin\DroneAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Drone" }
        arguments:
            - ~
            - Drone\MapBundle\Entity\Drone
            - ~
        calls:
            - [ setTranslationDomain, [DroneAdminBundle]]