drone_map_homepage:
    path:     /
    defaults: { _controller: DroneMapBundle:Default:index }

drone_map_add_field:
    path:     /add_field
    defaults: { _controller: DroneMapBundle:Default:addField }
    options:
        expose: true